### ISSUE TITLE
Final Project Check List

### ISSUE THREAD

**Issue by annarupert** [ecn310/course-project-accidentsteam#15]
This is our check list for our final project, mark when section is complete.
- [x] Abstract
- [x] Intro
- [x] Lit review
- [x] Data
- [x] Results
- [x] Discussion
- [x] Conclusion
- [ ] References / Bibliography

**Comment by annarupert** [comment]
@tomoyoshikun 
Can you please send me the list of sources in proper format so I can add to report? Thank you so much!

**Comment by tomoyoshikun** [comment]
> @tomoyoshikun 
> 
> Can you please send me the list of sources in proper format so I can add to report? Thank you so much!

I think I sourced everything on the goggle doc

**Comment by annarupert** [comment]
Documenation Check List

- [ ] Read Me Long
- [ ] Read Me Short 
- [ ] Output Analysis
- [ ] Data Appendix 
- [ ] Master Do-File 
- [ ] Place other Do-Files into Folder
