### ISSUE TITLE
First Draft Analysis Brain Storm 

### ISSUE THREAD

**Issue by annarupert** [ecn310/course-project-accidentsteam#17]
Yuhan and I are working on the first draft of our groups analysis. 

We decided that we are going to focus on `annual_average_employees` as a base and then use different variables to highlight a possible correlation between frim size and accidents. 

Yuhan will explain more below:

**Comment by annarupert** [comment]
@kbuzard Here is the box plot for the decile variable, let me know if you think this is worth while to add, if not I can discuss variance still for all of the variables because it was apart of the summary statistics. 
<img width="796" alt="Screen Shot 2023-12-04 at 11 30 41 PM" src="https://github.com/ecn310/course-project-accidentsteam/assets/143777952/28b77b38-6694-480c-9150-e96df450e3f3">

**Comment by kbuzard** [comment]
This is not what I was imagining. I agree this doesn't help very much.

Instead, I was imagining a box plot of the injury rate within each decile--so we wouldn't just see the average (which is on a bar chart), but also the dispersion

**Comment by annarupert** [comment]
I am having trouble creating that, whenever I put that in it comes out with to box plots. I am sure its a quick fix but I could not figure it out. @kbuzard

**Comment by kbuzard** [comment]
@annarupert I can work through it with you in office hours 2:30 to 3:30 in Eggers 131
