### ISSUE TITLE
Documentation Completion Plan 

### ISSUE THREAD

**Issue by annarupert** [ecn310/course-project-accidentsteam#21]
This is our Documentation plan for the rest of the semester! Let me know if you want me to add another row, I am sorting through a lot of information it may have slipped my mind. Thanks! Going to mention you as well so this is easy to find! @kbuzard 

All of this will be on GitHub so we will need a public repo! 

| Task | Completion Date | Person Responsible |
| ---- | ------------ | --------|
| Final Documentation | Dec 16| Will |
| Peer Check | Dec 15 | Anna |
| Fix Mistake | Dec 14 | Will |
| Documentation Test| Dec 14 | Tomoyoshi|
| Output of Analysis| Dec 14| Yuhan|
| Read.Me (Long) How we Documented the Data | Dec 13 | Will |
| Read.Me Short| Dec 13| Anna |
| Data Appendix | Dec 13| Yuhan |
| Fix and Add any Notes to Do.File | Dec 13/14| Anna|
| All Step by Step Do-Files Are Organized | Dec 12| Yuhan |
| Check Do-File| Dec 12 | Yuhan|
| Master-Do.File | Dec 12| Anna|
| Raw Data is not altered | In general |Will |

“Read.Me (Long) How we Documented the Data“ - this will be either in a separate file or put in the data appendix based on its size. Our opinion as of now is that it will not be that long and can be put in the appendix.

**Comment by kbuzard** [comment]
@ecn310/accidentsteam 

> Read.Me (Long) How we Documented the Data	

Make sure this includes how you downloaded the data (I think this is pretty easy in your case).

Also, make sure that the names and contact information of all the team members are in one of the READMEs.

This looks good to go!

**Comment by annarupert** [comment]
@wmwaghor 

Could you please start working on the large read.me and update here or in a new issue, I am going to office hours tomorrow and would love to add notes in case you need help or some ideas about structure.

**Comment by wmwaghor** [comment]
> @wmwaghor
> 
> Could you please start working on the large read.me and update here or in a new issue, I am going to office hours tomorrow and would love to add notes in case you need help or some ideas about structure.

Working on it now. Thanks

**Comment by annarupert** [comment]
@Yuhan-2435 Can you please send the output of analysis! there is infromation on it in issue #22

**Comment by annarupert** [comment]
@wmwaghor any updates? We are aiming to submit this project tomorrow night or early morning tuesday!

**Comment by Yuhan-2435** [comment]
> @Yuhan-2435 Can you please send the output of analysis! there is infromation on it in issue #22

I will try to get these done before tomorrow at 4pm. Sorry for the delay. I have exams these two days.
