### ISSUE TITLE
Output Analysis Completion 

### ISSUE THREAD

**Issue by annarupert** [ecn310/course-project-accidentsteam#22]
Log File 

All Graphs

**Comment by Yuhan-2435** [comment]
@annarupert Can you add only the LaTex code about making the graphs under the Reproducibility Package -> Output folder? I saw the example did that for their master documentation. Thank you!

**Comment by annarupert** [comment]
@Yuhan-2435 I have to do that when everything it completed and there is still feedback to work through.
