### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by annarupert** [ecn310/course-project-accidentsteam#24]
Insert abstract text here: 75-200 word, very high-level summary of your project.

**Comment by tomoyoshikun** [comment]
Working on now

**Comment by tomoyoshikun** [comment]
This research paper examines the different factors that may affect workplace safety. 
He has done research based on many types of factors such as the effect of unions, firm size, workplace inspections Etc. We have gotten our data from OCHA, a government agency that regulates Firm safety. From our research we found the main contributing factor to workplace safety is blank and the results indicate that blank

@annarupert is this good? not sure what to write in the end about what the main idea  is

**Comment by annarupert** [comment]
Thank you this is great! I will add the rest! @tomoyoshikun
