### ISSUE TITLE
Analysis Assignment Submission

### ISSUE THREAD

**Issue by annarupert** [ecn310/course-project-accidentsteam#25]
Big picture questions to answer: Given your hypothesis, how did you test it and what did you find? Your job is to persuade the reader that you approached the question in a sensible way. **See Greenlaw Chapter 12, pages 241-245 for details.**

To do this, make sure you include:
- discussion of the type of statistical analysis you employed (and why it is the right thing to do);

- the results you hypothesized (operationalize your hypothesis: how does it map into the variables you have?);
your actual results;

- Details about your data collection and each variable (including summary stats) should be in data section;

-  the figures in analysis section should show the relationships between the key variables, and perhaps more detail about important features of individual variables.

- your interpretation of the results.

- Compile the PDF of the report in LaTeX, save as “Projectname Analysis Draft” and upload the .tex and PDF to your Github repo

- Only the analysis section will be graded at this point; I’ll give you feedback on it by end of day Wednesday at the latest
First come, first served: turn it in early if it’s ready!

I’ll also give you feedback on any sections that are finished and answer any specific questions you have (may take a little longer)

Either delete the parts that aren't ready (or comment them out in the .tex file so they aren't included, following [these instructions](https://texblog.org/2007/12/31/commenting-in-latex/)) or add a comment in the PDF that tells me which sections to look at 

For full credit, out of a total of 10 points
- All four elements listed above must be included
- All planned analysis output must be included (no "to be completed" or "coming soon")
- I will give you feedback on the professionalism of the figure (see [rubric](https://github.com/ecn310/exercises/blob/main/Course%20Project%20Rubric.pdf) with new category added)
- The section must tell a coherent, complete, and persuasive story (reference: Greenlaw Ch. 4)
- I will not take off points for typos or grammar issues per se at this point, but at some point bad writing makes it hard to tell a coherent and persuasive story.
- Bonus point if 'all sentences are complete and grammatical. 
- All words are chosen for their precise meanings. All new or unusual terms are well-defined. Key concepts are completely explained. 
- Submission has been spell-checked and proofread and has no errors.' (the full credit clarity standard for the project in general).

**Comment by annarupert** [comment]
Hi team! I just submitted our current paper to our home page but I am adding it here in case anyone wants to to read an review it. 
[Accidents Team Analysis Draft.pdf](https://github.com/ecn310/course-project-accidentsteam/files/13647798/Accidents.Team.Analysis.Draft.pdf)

**Comment by kbuzard** [comment]
@annarupert Will you please also upload the .tex file to your home page? That's where I'm planning to leave comments.

**Comment by annarupert** [comment]
Yes they are there as well under report folder, I just used this to let me group know I submitted it on time. @kbuzard

**Comment by annarupert** [comment]
@kbuzard Yes, I forgot how to put it into a folder and that took some deleting and moving around, so I must have done that by accident. Sorry for the naming mistake, I thought that only applied to the pdf but looking back that does not make sense! Apologies for any confusion! 

- Also I am not sure if this is obvious but we should have all the details of the written portion of the paper done and ready to revised in that file. 
- We are missing documentation but we would love feedback on everything when possible, I know you said that would take longer which is fine just wanted to make it clear which portions to pay attention to. 

Thank you!!

**Comment by annarupert** [comment]
@kbuzard I can try and re add the tex file if that would be better for this process! Let me know and I will fix as soon as possible.

**Comment by kbuzard** [comment]
@annarupert It's no problem now that I know where it is. I'll just look at the one in the main folder.
