### ISSUE TITLE
Plan for Final Submission

### ISSUE THREAD

**Issue by annarupert** [ecn310/course-project-accidentsteam#26]
Here is a list of the tasks that need to be completed in order. Please do not complete any of these tasks without documenting them clearly on our repo. I am starting these now and should have everything except for the short readme completed by tomorrow at 3pm. @ecn310/accidentsteam 

- [x] Edit Abstract 
- [x] Edit Introduction 
- [x] Edit Lit Review
- [x] Edit Data 
- [x] Edit Analysis 
- [x] Edit Theories 
- [x] Edit Discussion
- [x] Edit Conclusion 
- [x] Include Finalized bibliography 
- [x] Master-Do File 
- [x] Long Read Me (Data Appendix)
- [x] Upload Onto Github
- [x] Clean Github 
- [x] Documentation Clean up
- [x] Short Read Me 
- [x] Peer Check

**Comment by annarupert** [comment]
@eldreddyl I know you are very busy, is there anyway you could glance at our documentation tomorrow and see if there are any last minute adds. If not no worries, we can find another peer to look at it. Thanks !

**Comment by annarupert** [comment]
@Yuhan-2435 Please document what you are doing!! There is little written detail and it is confusing to look through without detail.

**Comment by annarupert** [comment]
@Yuhan-2435  PLEASE ! do not delete any document or data without consulting members of the group. You deleted our original report file with all of the feedback from Dr.Buzard. Github allows us to get this information back but please be more mindful of the group and our plan for final submission.

**Comment by Yuhan-2435** [comment]
- I created a folder called Reproducibility Package, which contains subfolders: Data, Outputs. 
 - I put every do files that are related to data fixt, analysis under the Data folder. 
 - In the output folder, I put all the graph images under it. 
 - I renamed the final.do to Master.do and put it under the Reproducibility Package. If there is any editions on that do file, we can re-upload it. 
 - I am still working on the README.

**Comment by kbuzard** [comment]
@ecn310/accidentsteam If you just want to see the feedback (and not actually restore the file to the repository, this is pretty easy:
1. Click on "Pull requests" (it's in between Issues and Discussions)
2. Click on the "Feedback" pull request
3. Of the four choices toward the top of the page, click "Commits (87)"
4. Click on the one called "[TEX file](https://github.com/ecn310/course-project-accidentsteam/pull/1/commits/0a559943bf5d7424e6fa4363b971e83c78070829)"

If you want to actually restore that file, it's more complicated but I can show you how to do it.

**Comment by eldreddyl** [comment]
> If not no worries, we can find another peer to look at it.

Hi @annarupert unfortunately I won't have time to do this today, but let me know if you have any last minute questions and I'll do my best to answer them
